### ISSUE TITLE
年月日の数値に上限がない

### ISSUE THREAD

**Issue by yuuuni1211** [tes-inc/internship-development#19]
# 問題点
- 年月日の上限がないため、想定外の数値が入力されてしまう可能性がある。
# 解決策
- フォームとキーコード入力で上限を持たせる。

**Comment by yuuuni1211** [comment]
# 完了しました！

具体的には...
入力値に制限がなかったため、min maxで制限を持たせました。

**Comment by hashy0917** [comment]
手入力じゃなくてプルダウン形式に変えた方がいいのでは？
