### ISSUE TITLE
ユーザビリティ向上(アプリケーションの現状問題点)

### ISSUE THREAD

**Issue by yuuuni1211** [tes-inc/internship-development#2]
# 問題点を投げてください

**Comment by hashy0917** [comment]
* 検索ページの選択項目を適切なものに変更す
* 検索時のエラーをハンドリングして新たに作ったエラーページに誘導する

**Comment by yuuuni1211** [comment]
- フォーム入力で、負の値が入ってしまう。
- 性別の部分が現状数値である
- レイアウトが崩れており、視認性が悪い
- レスポンシブ対応していない

**Comment by yoshino199** [comment]
- お気に入り一覧に登録したものを削除することができない
- お気に入りに追加する際に名前を入力しないとお気に入り一覧から誕生日ページに飛べない
- 検索結果の誕生日ページに\</br>が表示される

**Comment by hashy0917** [comment]
* スマホに非対応

**Comment by hibikiNPC** [comment]
-url

**Comment by hashy0917** [comment]
* サインアウトできない

**Comment by yoshino199** [comment]
- 検索ページでなぜかeだけ数字以外で入力出来る（文字列で検索しようとするとエラーで止められはする）

**Comment by yuuuni1211** [comment]
close #2
