### ISSUE TITLE
user_idが全件1である

### ISSUE THREAD

**Issue by yuuuni1211** [tes-inc/internship-development#22]
# 問題点
- FavoriteDBのfavoritesテーブルのカラムuser_idが全件1である
# 解決策
- auto_incrementで連番にしてあげるか、user_idを毎回+1する処理をつける。

**Comment by tomoyami** [comment]
@yuuuni1211 
口頭でも説明しましたが念の為こちらでも。

`favorites`

|id|user_id|year|month|day|
|--:|--:|--:|--:|--:|
| 1 | 1 | 2000 | 1 | 1 |
| 2 | 1 | 2000 | 1 | 2 |
| 3 | 2 |  2000 | 1 | 1 |

`favorites` に定義している `user_id` カラムは、 `usersテーブルのid` との関連のために存在しています。
上記テーブルだと、user_id = 1であるユーザが2レコード保持していることになりますね。
（お気に入りの年月日を2件持っていることになります）

なので、このissueについてはバグではなく正常な状態になりますので、クローズしちゃってください。
