### ISSUE TITLE
TOPページを作成する

### ISSUE THREAD

**Issue by yuuuni1211** [tes-inc/internship-development#27]
# 提案
- TOPページがないため作成をする。

**Comment by hibikiNPC** [comment]
@yuuuni1211 
TOPページはありますけど、書くものがないですね
何を書けばいいんでしょうか？

**Comment by hibikiNPC** [comment]
2c22e951c51fcde04e855552e8160bf7c6c2a4ad にてTOPページが追加されました。
これ以上追加するものもなさそうですのでCloseにします
