### ISSUE TITLE
ユーザビリティの向上（改修のランク付け)

### ISSUE THREAD

**Issue by yuuuni1211** [tes-inc/internship-development#3]
# Must!!
- 空白タグが表示されるのを直す
- フォーム入力で負の数値を含めない
- サインアウトをできるようにする
- ドメインでアクセスできるようにする(アクセシビリティ)
- 性別を文字列にする
- ラジオボタン,プルダウン,リストなどで選択できるようにする
- 入力をしていなフォームがあればハイライトしてメッセージをだす
# 時間があれば...
- 削除機能
- レスポンシブ対応
- 日の入力でeが入力できる

> 何か追加があればコメントください

**Comment by yoshino199** [comment]
- お気に入り一覧のソートがちょっと怪しい
