### ISSUE TITLE
フォーム入力で、負の値が入ってしまう

### ISSUE THREAD

**Issue by tomoyami** [tes-inc/internship-development#8]
## 不具合詳細

フォーム入力で、負の値が入ってしまう

## 正しいこと

負の値を入力できないように制御する

**Comment by yuuuni1211** [comment]
正しく修正が完了しました。

#　具体的な方法としては
まずテキスト入力とキーコードでの入力の2パターンが存在するので、両方で制御する必要があったため、
`<input` type="number" min="0" oninput="this.value = `Math.abs(this.value)">`
のように、キーコードでは0を下限値にテキスト入力では、絶対値をしていすることによって、負の値を入力させないようにしました。
